### ISSUE TITLE
Booting macOS after install

### ISSUE THREAD

**Issue by fmorea** [d-graz/HP_Pavilion_X360_14-dh0023nl_Hackintosh#2]
I tried to install hackintosh following the guide:
1. Downloaded Mac os Ventura from a real mac
2. Installed onto an usb stick
3. Mounted the EFI folder and compied your EFI
4. Booted the laptop with the USB and installed Mac os
Unfortunately at the end of the installation I'm presented still with Windows Boot Manager (even if there is no more Windows!) 
Tried installing using both APFS and Mac Extended Journaled.
Probabily I'm too dumb and I'm doing something wrong.
![1](https://user-images.githubusercontent.com/91631198/229891104-2648a6ee-1cf2-43dd-b82e-70c501f98e1e.jpeg)
![2](https://user-images.githubusercontent.com/91631198/229891124-a946fef0-30cc-4f1f-bf2f-62edbdbb7faa.jpeg)

**Comment by d-graz** [comment]
Assuming that you have correctly executed step 1 to 3:
- from macOS Big Sur (I believe) you should install macOS on an APFS file-systems 
- When installing macOS the EFI present on your usb stick is not copied over your disk. This means that you can boot your macOS installation using the usb until you manually copy the EFI onto your laptop disk. You should check [this](https://dortania.github.io/OpenCore-Post-Install/universal/oc2hdd.html#grabbing-opencore-off-the-usb) guide on how to do it.

To boot installed macOS from the install usb just select the usb as boot device (as you did for install procedure) and then Opencore should automatically detect  your newly installed macOS partition

**Comment by fmorea** [comment]
After a lot of trials and errors, I found the solution:
the field "HideAuxiliary" inside your config.plist should be set to false (don't know why).

**Comment by d-graz** [comment]
From Opencore documentation:
![immagine](https://user-images.githubusercontent.com/101061140/230205284-1441ee76-976d-4450-87de-ba79cc4576b6.png)
So you can choose either to expose by default all entries or press spacebar key to see the auxiliary ones.  Although this is not very important, and it's up to you to decide this setting, I would like to report that opportunity.

That said i don't know why Opencore has flagged your macOS installation as auxiliary, but I'm glad you find out and fixed this issue.

**Comment by fmorea** [comment]
Everything works, congratulations for your work!
I would like to point out that the webcam also works, wifi is perfect (intel 3168ngw) both 5ghz and 2.4.
I'd like to get touch and pen to work.
Other issue: my laptop has another internal drive next to the nvme, and is not detected by mac os, probabily some kext is needed (I'll do some search).

**Comment by d-graz** [comment]
Check [this kext](https://github.com/dortania/OpenCore-Install-Guide/blob/master/extra-files/CtlnaAHCIPort.kext.zip) for your HDD
